"""
docgen.py — Compose the Program Documentation from the populated catalog.
Every numeric claim is a catalog query. Narrative prose is kept minimal and grounded.
"""
from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from pathlib import Path


@dataclass
class DocResult:
    md_path: str
    html_path: str
    executive_path: str


def synthesize(catalog_path: str | Path, workdir: str | Path, app_name: str,
               llm_summarizer=None) -> DocResult:
    """
    llm_summarizer: optional callable(prompt: str) -> str for generating case-type
    summaries. If None, a deterministic template is used instead.
    """
    workdir = Path(workdir)
    conn = sqlite3.connect(catalog_path)
    cur = conn.cursor()

    stats = _collect_stats(cur)
    case_types = _collect_case_types(cur)

    md_parts: list[str] = []
    md_parts.append(f"# Program Documentation — {app_name}\n")
    md_parts.append(f"*Generated by PegaRE from {stats['rule_total']} rules across {len(stats['rulesets'])} rulesets.*\n")

    # 1. Executive summary
    md_parts.append("## 1. Executive Summary\n")
    md_parts.append(_executive_summary(stats, case_types, llm_summarizer))

    # 2. Application Hierarchy
    md_parts.append("## 2. Application Hierarchy\n")
    md_parts.append(_hierarchy_section(cur, stats))

    # 3. Case Types
    md_parts.append("## 3. Case Types\n")
    for ct in case_types:
        md_parts.append(_case_type_section(cur, ct, llm_summarizer))

    # 4. Task Ledger
    md_parts.append("## 4. Task Generation Ledger\n")
    md_parts.append(_task_ledger_section(cur, stats))

    # 5. UI Catalog
    md_parts.append("## 5. UI Catalog\n")
    md_parts.append(_ui_section(cur, stats))

    # 6. Dependency / orphans (light-weight)
    md_parts.append("## 6. Rule Usage\n")
    md_parts.append(_usage_section(cur))

    # 7. Review queue
    md_parts.append("## 7. Review Queue\n")
    md_parts.append(_review_queue(cur))

    md = "\n".join(md_parts)
    md_path = workdir / "program_doc.md"
    md_path.write_text(md)

    html_path = workdir / "program_doc.html"
    html_path.write_text(_wrap_html(md, app_name))

    exec_path = workdir / "executive_summary.md"
    exec_path.write_text(_executive_one_pager(app_name, stats, case_types))

    conn.close()
    return DocResult(md_path=str(md_path), html_path=str(html_path), executive_path=str(exec_path))


def _collect_stats(cur: sqlite3.Cursor) -> dict:
    stats = {}
    stats["rule_total"] = cur.execute("SELECT COUNT(*) FROM rules WHERE parsed_ok=1").fetchone()[0]
    stats["rulesets"] = [r[0] for r in cur.execute(
        "SELECT DISTINCT ruleset FROM rules WHERE ruleset IS NOT NULL ORDER BY ruleset"
    ).fetchall() if r[0]]
    stats["case_types"] = cur.execute("SELECT COUNT(*) FROM case_types").fetchone()[0]
    stats["assignments"] = cur.execute("SELECT COUNT(*) FROM assignments").fetchone()[0]
    stats["flows"] = cur.execute("SELECT COUNT(*) FROM flows").fetchone()[0]
    stats["harnesses"] = cur.execute("SELECT COUNT(*) FROM ui_rules WHERE ui_type='harness'").fetchone()[0]
    stats["sections"] = cur.execute("SELECT COUNT(*) FROM ui_rules WHERE ui_type='section'").fetchone()[0]
    stats["classes"] = cur.execute("SELECT COUNT(*) FROM classes").fetchone()[0]
    stats["properties"] = cur.execute("SELECT COUNT(*) FROM properties").fetchone()[0]
    stats["parse_failures"] = cur.execute("SELECT COUNT(*) FROM rules WHERE parsed_ok=0").fetchone()[0]
    stats["unknown_rule_types"] = cur.execute("SELECT COUNT(*) FROM unknown_rule_types").fetchone()[0]
    stats["partial_ui"] = cur.execute("SELECT COUNT(*) FROM ui_rules WHERE fidelity='partial'").fetchone()[0]
    stats["stub_ui"] = cur.execute("SELECT COUNT(*) FROM ui_rules WHERE fidelity='stub'").fetchone()[0]
    return stats


def _collect_case_types(cur: sqlite3.Cursor) -> list[dict]:
    rows = cur.execute(
        "SELECT case_type_id, class_name, label, starting_flow, stage_count FROM case_types ORDER BY label"
    ).fetchall()
    out = []
    for ct_id, cls, label, start, sc in rows:
        out.append({"id": ct_id, "class_name": cls, "label": label or cls, "starting_flow": start, "stage_count": sc})
    return out


def _executive_summary(stats, case_types, llm) -> str:
    lines = []
    lines.append(f"**Scale.** {stats['rule_total']:,} rules, {stats['classes']:,} classes, "
                 f"{stats['case_types']} Case Types, {stats['flows']:,} flows, "
                 f"{stats['assignments']:,} generated tasks, {stats['harnesses']} harnesses.")
    lines.append(f"**Rulesets** in scope: {', '.join(stats['rulesets'][:10])}"
                 + (f" (+{len(stats['rulesets'])-10} more)" if len(stats['rulesets']) > 10 else "") + ".")
    if case_types:
        names = ", ".join(ct["label"] for ct in case_types[:8])
        lines.append(f"**Top Case Types:** {names}.")
    risks = []
    if stats["parse_failures"]:
        risks.append(f"{stats['parse_failures']:,} rules failed to parse")
    if stats["unknown_rule_types"]:
        risks.append(f"{stats['unknown_rule_types']} unknown rule types")
    if stats["stub_ui"]:
        risks.append(f"{stats['stub_ui']} UI rules rendered only as stubs")
    if risks:
        lines.append("**Known risks:** " + "; ".join(risks) + ".")
    return "\n\n".join(lines) + "\n"


def _hierarchy_section(cur, stats) -> str:
    out = []
    out.append(f"- **Classes:** {stats['classes']:,} ({cur.execute('SELECT COUNT(*) FROM classes WHERE is_work_class=1').fetchone()[0]} work, "
               f"{cur.execute('SELECT COUNT(*) FROM classes WHERE is_data_class=1').fetchone()[0]} data)")
    out.append(f"- **Properties:** {stats['properties']:,}")
    out.append(f"- **Access Roles:** {cur.execute('SELECT COUNT(DISTINCT role_name) FROM access_roles').fetchone()[0]}")
    out.append("")
    out.append("### Rulesets")
    out.append("| Ruleset | Rules |")
    out.append("|---|---:|")
    rs = cur.execute("SELECT ruleset, COUNT(*) FROM rules WHERE parsed_ok=1 GROUP BY ruleset ORDER BY 2 DESC LIMIT 30").fetchall()
    for r, c in rs:
        out.append(f"| {r or '(none)'} | {c:,} |")
    out.append("")
    out.append("Full class tree: [`hierarchy.html`](hierarchy.html)")
    return "\n".join(out) + "\n"


def _case_type_section(cur, ct, llm) -> str:
    stages = cur.execute(
        "SELECT stage_id, label, stage_order, stage_type FROM stages WHERE case_type_id=? ORDER BY stage_order",
        (ct["id"],)
    ).fetchall()
    out = [f"### 3.{ct['id']} {ct['label']}"]
    out.append(f"*Class:* `{ct['class_name']}` · *Starting flow:* `{ct['starting_flow']}` · *Stages:* {ct['stage_count']}")
    # Purpose paragraph
    purpose = _case_type_purpose(ct, stages, llm)
    out.append("")
    out.append(purpose)
    out.append("")
    # Stages / steps table
    out.append("| # | Stage | Type | Steps |")
    out.append("|--:|---|---|---|")
    for sid, slabel, sorder, stype in stages:
        step_rows = cur.execute(
            "SELECT label, flow_ref FROM steps WHERE stage_id=? ORDER BY step_order", (sid,)
        ).fetchall()
        step_str = "; ".join(f"{lbl or fr}" for lbl, fr in step_rows) or "(no steps)"
        out.append(f"| {sorder+1} | {slabel} | {stype} | {step_str} |")
    # Tasks for this case type
    task_count = cur.execute("SELECT COUNT(*) FROM assignments WHERE case_type_id=?", (ct["id"],)).fetchone()[0]
    out.append("")
    out.append(f"**Tasks generated:** {task_count} (see [task_ledger.html](task_ledger.html), filter by `{ct['label']}`)")
    out.append(f"**Process diagram:** [case_type_{ct['id']}.html](case_type_{ct['id']}.html)")
    return "\n".join(out) + "\n"


def _case_type_purpose(ct, stages, llm) -> str:
    stage_names = [s[1] for s in stages if s[1]]
    if llm and stage_names:
        prompt = (
            f"Summarise the Pega Case Type '{ct['label']}' (class {ct['class_name']}) in 3-5 sentences. "
            f"Its stages are: {', '.join(stage_names)}. "
            f"Ground every sentence in these stage names. Do not invent business purpose."
        )
        try:
            return llm(prompt).strip()
        except Exception:
            pass
    # Deterministic fallback
    if not stage_names:
        return "Insufficient structural evidence to summarise — see tables below."
    return (f"Case Type *{ct['label']}* progresses through the stages: **{' → '.join(stage_names)}**. "
            f"Each stage sequences one or more flows that generate assignments routed to operators or workbaskets. "
            f"Detailed task and SLA breakdowns are in the ledger.")


def _task_ledger_section(cur, stats) -> str:
    out = [f"Total assignments: **{stats['assignments']:,}**. Full filterable ledger: [task_ledger.html](task_ledger.html)."]
    # Router breakdown
    rows = cur.execute(
        "SELECT router_type, COUNT(*) FROM assignments GROUP BY router_type ORDER BY 2 DESC"
    ).fetchall()
    if rows:
        out.append("\n### By router type\n")
        out.append("| Router Type | Tasks |\n|---|---:|")
        for rt, c in rows:
            out.append(f"| {rt or '(unknown)'} | {c:,} |")
    # SLA hotspots
    out.append("\n### SLA hotspots (shortest deadlines)\n")
    rows = cur.execute(
        "SELECT case_type_label, task_label, sla_rule, sla_deadline_mins FROM assignments "
        "WHERE sla_deadline_mins IS NOT NULL ORDER BY sla_deadline_mins ASC LIMIT 20"
    ).fetchall()
    if rows:
        out.append("| Case Type | Task | SLA | Deadline (min) |\n|---|---|---|---:|")
        for ctl, tl, sla, dl in rows:
            out.append(f"| {ctl} | {tl} | {sla} | {dl} |")
    else:
        out.append("_No SLAs resolved_")
    return "\n".join(out) + "\n"


def _ui_section(cur, stats) -> str:
    out = [f"- **Harnesses:** {stats['harnesses']}",
           f"- **Sections:** {stats['sections']}",
           f"- **Partial fidelity:** {stats['partial_ui']}",
           f"- **Stub fidelity:** {stats['stub_ui']}",
           "",
           "Full UI catalog: [ui/index.html](ui/index.html)"]
    return "\n".join(out) + "\n"


def _usage_section(cur) -> str:
    out = ["Top rule classes by count:"]
    rows = cur.execute(
        "SELECT obj_class, COUNT(*) FROM rules WHERE parsed_ok=1 GROUP BY obj_class ORDER BY 2 DESC LIMIT 20"
    ).fetchall()
    out.append("| Rule Type | Count |\n|---|---:|")
    for oc, c in rows:
        out.append(f"| {oc} | {c:,} |")
    return "\n".join(out) + "\n"


def _review_queue(cur) -> str:
    out = []
    failed = cur.execute("SELECT COUNT(*) FROM rules WHERE parsed_ok=0").fetchone()[0]
    unknown = cur.execute(
        "SELECT obj_class, count FROM unknown_rule_types ORDER BY count DESC LIMIT 20"
    ).fetchall()
    out.append(f"- Parse failures: **{failed}**")
    if unknown:
        out.append("- Unknown rule types detected:\n")
        out.append("| Obj Class | Count |\n|---|---:|")
        for oc, c in unknown:
            out.append(f"| {oc} | {c:,} |")
    stub = cur.execute(
        "SELECT class_name, name FROM ui_rules WHERE fidelity='stub' LIMIT 20"
    ).fetchall()
    if stub:
        out.append("\n- Stub-fidelity UI rules (sample):\n")
        for cls, name in stub:
            out.append(f"  - {cls}.{name}")
    return "\n".join(out) + "\n"


def _executive_one_pager(app_name, stats, case_types) -> str:
    return f"""# {app_name} — Executive Summary

**What it is.** A Pega application with {stats['case_types']} Case Types and {stats['rule_total']:,} rules across {len(stats['rulesets'])} rulesets.

**Top Case Types:** {', '.join(ct['label'] for ct in case_types[:6])}.

**Volume of work it generates:** {stats['assignments']:,} distinct task types across {stats['flows']:,} flows.

**User surfaces:** {stats['harnesses']} full screens (harnesses), {stats['sections']} reusable sections.

**Risks flagged for review:**
- {stats['parse_failures']:,} rules failed to parse
- {stats['unknown_rule_types']} unknown rule types (new / custom)
- {stats['stub_ui']} UI rules that could only be rendered as stubs

See `program_doc.html` for the full navigable documentation.
"""


def _wrap_html(md: str, title: str) -> str:
    # Lightweight markdown → HTML (headings, tables, links)
    import html as _html
    lines = md.split("\n")
    out = []
    in_table = False
    for ln in lines:
        if ln.startswith("# "):
            out.append(f"<h1>{_html.escape(ln[2:])}</h1>")
        elif ln.startswith("## "):
            out.append(f"<h2>{_html.escape(ln[3:])}</h2>")
        elif ln.startswith("### "):
            out.append(f"<h3>{_html.escape(ln[4:])}</h3>")
        elif ln.startswith("|"):
            if not in_table:
                out.append("<table>")
                in_table = True
            cells = [c.strip() for c in ln.strip("|").split("|")]
            if all(set(c) <= set("-: ") for c in cells):
                continue
            tag = "th" if (len(out) and out[-1] == "<table>") else "td"
            out.append("<tr>" + "".join(f"<{tag}>{_html.escape(c)}</{tag}>" for c in cells) + "</tr>")
        else:
            if in_table:
                out.append("</table>")
                in_table = False
            if ln.strip():
                # crude links and bolds
                import re
                ln2 = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', ln)
                ln2 = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", ln2)
                ln2 = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", ln2)
                out.append(f"<p>{ln2}</p>")
    if in_table:
        out.append("</table>")
    body = "\n".join(out)
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>{title}</title>
<style>
body{{font-family:-apple-system,Segoe UI,sans-serif;max-width:1000px;margin:20px auto;padding:0 20px;color:#1a2332;line-height:1.55}}
h1,h2,h3{{color:#0a1929}}
h1{{border-bottom:3px solid #d4a017;padding-bottom:8px}}
h2{{margin-top:2em;border-bottom:1px solid #d0d7de;padding-bottom:4px}}
table{{border-collapse:collapse;margin:10px 0;width:100%}}
td,th{{border:1px solid #d0d7de;padding:6px 10px;font-size:14px;text-align:left}}
th{{background:#0a1929;color:#fff}}
a{{color:#0a5c9a;text-decoration:none}}
a:hover{{text-decoration:underline}}
code{{background:#f4f6f9;padding:1px 4px;border-radius:2px;font-size:13px}}
</style></head><body>{body}</body></html>"""
